services:
  app:
    depends_on:
      - postgres
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"
    restart: always

  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    volumes:
      - type: bind
        source: ${SOURCE_MOUNTS_PATH}/db
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
